spring:
  application:
    name: fraud-rule-engine
  datasource:
    url: jdbc:h2:mem:frauddb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  cloud:
    function:
      definition: transactionEventConsumer
    stream:
      bindings:
        transactionEventConsumer-in-0:
          destination: ${app.kafka.transaction-topic}
          group: fraud-engine-group
          content-type: text/plain;charset=UTF-8
        transactionEventProducer:
          destination: ${app.kafka.transaction-topic}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: com.capitec.fraudengine.model

app:
  kafka:
    transaction-topic: transactions
